### ISSUE TITLE
Auto full screen

### ISSUE THREAD

**Issue by PierreScerri** [KTibow/fullscreen-card#3]
Hi

Is it possible to make this action automatic so that it goes to fullscreen when home assistant is accessed?

Is this card meant for desktops/laptops only because it does not work on an iPad/iPhone using Chrome?

Thank you.

**Comment by KTibow** [comment]
No, you'll have to use the official app and configure it, or Fully, because for security reasons the user has to initiate the fullscreen action.

**Comment by PierreScerri** [comment]
Pity.  Seemed useful

**Comment by KTibow** [comment]
Could you still manually initiate fullscreen?

**Comment by PierreScerri** [comment]
Only on my iMac, not the iPhone and iPad.

**Comment by KTibow** [comment]
Odd, do any other sites fullscreen work, like YouTube?

**Comment by PierreScerri** [comment]
Fullscreen works on Youtube on all my devices.

**Comment by KTibow** [comment]
Does this one work: https://www.w3schools.com/howto/howto_js_fullscreen.asp

**Comment by PierreScerri** [comment]
Sorry for the late reply.  Yes it works.

**Comment by KTibow** [comment]
Sorry this couldn't work.
