### ISSUE TITLE
Error in home-assistang.log

### ISSUE THREAD

**Issue by ChrisPiel70** [KTibow/fullscreen-card#4]
Just used "Fullscreen" a couple of times and saw these Errors in HA log everytime. 

Fullscreen-card does work though.

ERROR (MainThread) [frontend.js.latest.202010214] http://XXX.XXX.XXX.XXX:8123/hacsfiles/fullscreen-card/fullscreen-card.js:8:21 Uncaught ReferenceError: config is not defined

**Comment by KTibow** [comment]
Which version do you have? It's probably Uglify.

**Comment by ChrisPiel70** [comment]
Sorry, completely forget to supply infos.

HA 0.117.5 (VENV PY 3.8) with fullscreen-card 0.5. 

Have removed with HACS and done a new install. Still get the error message (from PC Browser and HA Android App).

Fullscreen-card still works as expected, its just the message in HA log file.

**Comment by KTibow** [comment]
Go into `hacs`' community folder (`/config/www/community/fullscreen-card`) and delete the `gz` file. Replace these two lines in the `js` file:
```
this.atag.innerHTML=config.go_fullscreen||(config.go_fullscreen="Go fullscreen")):(document.documentElement.requestFullscreen(),
this.atag.innerHTML=config.exit_fullscreen||(config.exit_fullscreen="Exit fullscreen")),this.fullscreen=!this.fullscreen}.bind(this),
```
with this:
```
this.atag.innerHTML=this.config.go_fullscreen||(this.config.go_fullscreen="Go fullscreen")):(document.documentElement.requestFullscreen(),
this.atag.innerHTML=this.config.exit_fullscreen||(this.config.exit_fullscreen="Exit fullscreen")),this.fullscreen=!this.fullscreen}.bind(this),
```
Hit save, press Ctrl/Command+Shift+R, and see if it fixes it.

**Comment by ChrisPiel70** [comment]
Have change the 2 lines and reloaded the script in HA and refreshed the browser cache

Fullscreen-card still works as expected in frontend and I now get a differnet error message in HA.log.

ERROR (MainThread) [frontend.js.latest.202010214] http://XXX.XXx.XXX.XXX:8123/hacsfiles/fullscreen-card/fullscreen-card.js:8:78 Uncaught TypeError: Cannot add property exit_fullscreen, object is not extensible

**Comment by KTibow** [comment]
Try replacing with this then:
```
this.atag.innerHTML=this.config.go_fullscreen||"Go fullscreen"):(document.documentElement.requestFullscreen(),
this.atag.innerHTML=this.config.exit_fullscreen||"Exit fullscreen"),this.fullscreen=!this.fullscreen}.bind(this),
```

**Comment by ChrisPiel70** [comment]
Have change the 2 lines and reloaded the script in HA and refreshed the browser cache

Fullscreen-card still works as expected in frontend and I now get a another different error message in HA.log.

ERROR (MainThread) [frontend.js.latest.202010214] http://XXX.XXX.XXX.XXX:8123/hacsfiles/fullscreen-card/fullscreen-card.js:10:76 Uncaught TypeError: Cannot read property 'push' of undefined

As it seems that I am the only one with this Problem, please don't waste any more of your time. 

Thank you for trying to resolve the problem.

**Comment by KTibow** [comment]
Nope, I get it too. Let me try to fix this...
