### ISSUE TITLE
Any chance of intergration with kiosk-mode?

### ISSUE THREAD

**Issue by Littleislandbrewing** [KTibow/fullscreen-card#5]
Is there any chance of calling this like kiosk-mode is called at the head of a lovelace dashboard????

Im trying to make a seamless kiosk and while kiosk-mode gets rid of the HA headers and sides, the browser navigation still shows up.

Trying to ensure that users go straight into fullscreen without having to use a button

**Comment by KTibow** [comment]
no idea, i'm not really doing as much ha dev and i don't know how kiosk-mode works (plus its archived?)
however i can tell you in order to go fullscreen the user has to click on something, that's the rule

**Comment by KTibow** [comment]
closing this as i can't help you with this
maybe @elchininet could help?

**Comment by elchininet** [comment]
Hi @KTibow,
Unfortunately, [I cannot help @Littleislandbrewing either](https://github.com/NemesisRE/kiosk-mode/issues/70), interaction from the user is required to enter in full-screen and nothing can be done to mitigate that.
Regards
