### ISSUE TITLE
Feature request: allow changing of colours

### ISSUE THREAD

**Issue by loryanstrant** [KTibow/fullscreen-card#8]
Any chance of being able to change the colour of the button and/or text?
I use a dark background, so the blue button stands out quite visibly compared to the rest of the buttons.
![image](https://github.com/KTibow/fullscreen-card/assets/51473494/c6f16c25-0f7d-490c-be11-e95def786e00)

**Comment by KTibow** [comment]
Is using card-mod an option for you? You can assign different values for `--primary-color` then.

**Comment by loryanstrant** [comment]
Thanks, that did the trick! Didn't even think of it. :-/
